version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certificates:/etc/ssl-certificates:ro
      - ./nginx/www:/var/www:ro
